## Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [1]:
import numpy as np

In [6]:
# Create a 1D array
arr=np.arange(1,13)
print(arr)
print(arr.shape) #(row,column) ->(12) i.e 12 is column
print(arr.ndim)
# Reshape it into 2D array
reshape_arr=arr.reshape(3,4)
print(reshape_arr)
print(reshape_arr.shape)
print(reshape_arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [7]:
# Reshape it to 3-D
reshape_arr3d=arr.reshape(2,3,2)
print(reshape_arr3d)
print(reshape_arr3d.shape)
print(reshape_arr3d.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [9]:
arr_3d=reshape_arr.reshape(3,1,-1)
print(arr_3d)
print(arr_3d.ndim)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
3


### Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

### Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

`Note: We can not pass -1 to more than one dimension.`

In [12]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements
arr=np.arange(1,9)
new_arr=arr.reshape(3,3)
print(new_arr)

ValueError: cannot reshape array of size 8 into shape (3,3)

## Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.



In [13]:
print(arr_3d)
flatten_arr=arr_3d.flatten()
print(flatten_arr)
print(flatten_arr.shape)
print(flatten_arr.ndim)

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


## What is Broadcasting?

Broadcasting is a NumPy feature that allows:
- Arithmetic operations on arrays of different shapes
- Automatic expansion of smaller arrays
- Writing less code with better performance

Broadcasting avoids explicit loops.


## Why Broadcasting is Important?

Broadcasting helps to:
- Perform operations faster
- Write clean and readable code
- Work efficiently with large datasets

This is heavily used in:
- Data Science
- Machine Learning
- Scientific computing


## Broadcasting Rules (Concept)

For two arrays to be broadcast together:
1. Compare shapes from right to left
2. Dimensions must be equal OR one of them must be 1
3. Missing dimensions are treated as size 1


## Scalar and Array Broadcasting

A scalar can be broadcast to match the shape of an array.


In [14]:
# Create a NumPy array
arr = np.array([1,2,3,4,5])

# Add a scalar value to the array
new_arr=arr+3

print(new_arr)

[4 5 6 7 8]


## Broadcasting Between 1D Arrays

Arrays with the same shape can be operated element-wise.



In [17]:
# Create two 1D arrays of same length
a=np.arange(1,4)
b=np.arange(4,7)
print(a)
print(b)

# Perform element-wise addition
print(a+b)

[1 2 3]
[4 5 6]
[5 7 9]


## Broadcasting Between 2D Array and 1D Array

A 1D array can be broadcast across rows or columns of a 2D array.


array    row   column
2d       2     3
1d       1     3

In [19]:
# Create a 2D array
a=np.array([

    [1,2,3],
    [4,5,6]
]
)
print(a.shape)
# Create a 1D array
b=np.array([10,20,30])
print(b.shape)

# Perform addition using broadcasting
print(a+b)

(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]


array| row| column
a         1  3
b         1   2

In [20]:
a=np.array([1,2,3])
print(a.shape)

b=np.array([4,5])
print(b.shape)

print(a+b)


(3,)
(2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Broadcasting with Column Vector

Broadcasting also works when shapes align using dimensions of size 1.


In [23]:
# Create a 2D array
matrix = np.array([
    [1,2,3],
    [4,5,6]
    ,
    [7,8,9]], ndmin=2)
print(matrix)

# Create a column vector (shape: n x 1)
column_vector=np.array([[10],[20],[30]])
print(column_vector)
print(column_vector.shape)
# Perform broadcasting operation
print(matrix * column_vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10]
 [20]
 [30]]
(3, 1)
[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


## Broadcasting Errors (Shape Mismatch)

If broadcasting rules are not satisfied, NumPy raises an error.


In [24]:
# Create two arrays with incompatible shapes
a=np.array([1,2,3])
print(a.shape)

b=np.array([4,5])
print(b.shape)



# Try to perform an operation and observe the error
print(a+b)


(3,)
(2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## What are Vectorized Operations?

Vectorized operations allow:
- Performing operations on entire arrays
- Without using loops
- With better performance


## Vectorized Operations vs Loops

| Loop | Vectorized |
|----|-----------|
| Slow | Fast |
| More code | Less code |
| Python-level | C-level (NumPy) |


In [25]:
# Create a NumPy array
arr=np.array([10,20,30,40])


# Perform vectorized addition
print(arr+3)

[13 23 33 43]


## Vectorized Mathematical Operations

NumPy supports vectorized math functions such as:
- add
- subtract
- multiply
- divide


In [28]:
# Create two NumPy arrays
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])

# Perform element-wise addition
print("Addittion:",a+b)

# Perform element-wise multiplication
print("Multiplication:",a*b)

Addittion: [11 22 33 44 55]
Multiplication: [ 10  40  90 160 250]


In [ ]:
a=np.arange(1,7).reshape(2,3)
print(a)
b=np

[[1 2 3]
 [4 5 6]]


## Vectorized Comparison Operations

Vectorized comparisons return boolean arrays.


In [31]:
# Create a NumPy array
arr=np.array([5,10,15,20,25])

# Compare array elements with a value
comparison=arr>15
print(comparison)

[False False False  True  True]


## Boolean Masking (Using Vectorization)

Boolean arrays can be used to filter data.


In [32]:
# Create a NumPy array
arr=np.array([5,10,15,20,25])

# Create a boolean condition
comparison=arr>15
print(comparison)

# Filter array using condition
filter_arr=arr[comparison]
print(filter_arr)

[False False False  True  True]
[20 25]


In [2]:
arr=np.arange(1,11)
print(arr)
comparison=  (arr%3)==0
print(comparison)
filter_arr=arr[comparison]
print(filter_arr)


[ 1  2  3  4  5  6  7  8  9 10]
[False False  True False False  True False False  True False]
[3 6 9]


## Broadcasting with Mathematical Functions

NumPy mathematical functions also support broadcasting.


In [5]:
# Create a NumPy array
arr=np.array([4,9,16,25,36])

# Apply a mathematical function to the array
print((np.sqrt(arr)))

[2. 3. 4. 5. 6.]
